var dashboardTemplate="";
dashboardTemplate += "<toaster-container toaster-options=\"{'time-out': 3000}\"><\/toaster-container>";
dashboardTemplate += "";
dashboardTemplate += "<div>";
dashboardTemplate += "    <div class=\"row clearfix\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <b>Gamma dashboardTemplate ver {{version}}<\/b>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <div class=\"panel panel-default\">";
dashboardTemplate += "                <div class=\"panel-heading\">";
dashboardTemplate += "                    <h3 class=\"panel-title\">";
dashboardTemplate += "                        Gamma dashboardTemplate";
dashboardTemplate += "                    <\/h3>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "                <div class=\"panel-body\">";
dashboardTemplate += "                    <div class=\"btn-group\" role=\"group\" aria-label=\"...\">";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Parse()\">";
dashboardTemplate += "                            Parse";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-primary\" ng-click=\"Download()\" ng-disabled=\"!isDone\">";
dashboardTemplate += "                            Download All";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"submit\" class=\"btn btn-danger\" ng-click=\"Stop()\">";
dashboardTemplate += "                            Stop";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                        <button type=\"button\" class=\"btn btn btn-default\" ng-csv=\"getArrayForCsv()\"";
dashboardTemplate += "                                filename=\"dashboardTemplate.csv\"";
dashboardTemplate += "                                csv-header=\"['Username', 'TotalQB', 'Rebates', 'TotalProductVoucher','ActiveAccnt','NewEntry','ReadyRorEncashment','EncashmentHistory']\">";
dashboardTemplate += "                            Export";
dashboardTemplate += "                        <\/button>";
dashboardTemplate += "                    <\/div>";
dashboardTemplate += "                    <table class=\"table\">";
dashboardTemplate += "                        <thead>";
dashboardTemplate += "                        <tr>";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                #";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                Booking Code";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                Passenger Name";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                            <th>State<\/th>";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                Promo Code";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                Meter Fare";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                Status";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                        <\/tr>";
dashboardTemplate += "                        <\/thead>";
dashboardTemplate += "                        <tbody>";
dashboardTemplate += "                        <tr ng-repeat=\"user in users\">";
dashboardTemplate += "                            <td>";
dashboardTemplate += "                                <span ng-bind=\"user.bookingCode\"\/>";
dashboardTemplate += "                            <\/td>";
dashboardTemplate += "                            <td>";
dashboardTemplate += "                                <span ng-bind=\"user.passenger\"\/>";
dashboardTemplate += "                            <\/td>";
dashboardTemplate += "                            <td>";
dashboardTemplate += "                                <span ng-bind=\"user.state\"\/>";
dashboardTemplate += "                            <\/td>";
dashboardTemplate += "                            <td><span ng-bind=\"user.amount\"\/><\/td>";
dashboardTemplate += "                            <td ng-class=\"{danger: user.IsError, success: user.IsSuccess}\">";
dashboardTemplate += "                                {{user.Status}}";
dashboardTemplate += "                            <\/td>";
dashboardTemplate += "                            <td>";
dashboardTemplate += "                                <input type=\"checkbox\" ng-model=\"user.WasDownloaded\"\/>";
dashboardTemplate += "                            <\/td>";
dashboardTemplate += "                            <td>";
dashboardTemplate += "                                <button ng-click=\"LoginToDownloadOneItem(user)\" ng-disabled=\"!isDone\">";
dashboardTemplate += "                                    {{user.DownloadBtn}}";
dashboardTemplate += "                                <\/button>";
dashboardTemplate += "                            <\/td>";
dashboardTemplate += "                        <\/tr>";
dashboardTemplate += "                        <\/tbody>";
dashboardTemplate += "                    <\/table>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "            <\/div>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "    <div class=\"row clearfix\" ng-show=\"isInputFieldsAreValid\">";
dashboardTemplate += "        <div class=\"col-md-12 column\">";
dashboardTemplate += "            <div class=\"panel panel-default\">";
dashboardTemplate += "                <div class=\"panel-heading\">";
dashboardTemplate += "                    <h3 class=\"panel-title\">";
dashboardTemplate += "                        Logs";
dashboardTemplate += "                    <\/h3>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "                <div class=\"panel-body\">";
dashboardTemplate += "                    <table>";
dashboardTemplate += "                        <tr ng-repeat=\"log in logs.slice().reverse() track by $index\">";
dashboardTemplate += "                            <th>";
dashboardTemplate += "                                {{log}}";
dashboardTemplate += "                            <\/th>";
dashboardTemplate += "                        <\/tr>";
dashboardTemplate += "                    <\/table>";
dashboardTemplate += "                <\/div>";
dashboardTemplate += "            <\/div>";
dashboardTemplate += "        <\/div>";
dashboardTemplate += "    <\/div>";
dashboardTemplate += "<\/div>";
dashboardTemplate += "";
